use std::ffi::OsStr;
use std::fs;
use std::io::{Error, ErrorKind};
use std::path::{Path, PathBuf};
use std::process::Command;

use golden_codegen_support::generate_app_nodes;

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is not set"));
    let bundled_ui_dir = out_dir.join("ui-dist");

    build_ui_bundle(&bundled_ui_dir).expect("failed to build bundled UI");
    generate_ui_assets_module(&bundled_ui_dir, &out_dir.join("ui_assets.rs"))
        .expect("failed to generate bundled UI asset module");

    tauri_build::build();

    let src_root = Path::new("src");
    generate_app_nodes(src_root, &out_dir.join("app_nodes.rs"));
}

fn build_ui_bundle(dist_dir: &Path) -> std::io::Result<()> {
    let ui_root = PathBuf::from("src-ui");
    track_ui_inputs(&ui_root)?;

    if !ui_root.join("node_modules").exists() {
        run_npm_command(&ui_root, &["ci"], &[])?;
    }

    if dist_dir.exists() {
        fs::remove_dir_all(dist_dir)?;
    }
    fs::create_dir_all(dist_dir)?;

    run_npm_command(&ui_root, &["run", "build"], &[("GC_UI_OUT_DIR", dist_dir.as_os_str())])
}

fn track_ui_inputs(ui_root: &Path) -> std::io::Result<()> {
    for relative in [
        "package.json",
        "package-lock.json",
        "svelte.config.js",
        "vite.config.ts",
        "src/app.html",
    ] {
        println!("cargo:rerun-if-changed={}", ui_root.join(relative).display());
    }

    emit_rerun_if_changed_for_dir(&ui_root.join("src"))?;
    emit_rerun_if_changed_for_dir(&ui_root.join("static"))?;

    Ok(())
}

fn emit_rerun_if_changed_for_dir(dir: &Path) -> std::io::Result<()> {
    if !dir.exists() {
        return Ok(());
    }

    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries = fs::read_dir(dir)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            emit_rerun_if_changed_for_dir(&path)?;
        } else {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    Ok(())
}

fn run_npm_command(ui_root: &Path, args: &[&str], envs: &[(&str, &OsStr)]) -> std::io::Result<()> {
    let npm = if cfg!(windows) { "npm.cmd" } else { "npm" };
    let mut command = Command::new(npm);
    command.args(args).current_dir(ui_root);
    for (key, value) in envs {
        command.env(key, value);
    }
    let status = command
        .status()
        .map_err(|err| Error::new(err.kind(), format!("failed to start {npm} {}: {err}", args.join(" "))))?;

    if status.success() {
        return Ok(());
    }

    Err(Error::new(
        ErrorKind::Other,
        format!("{npm} {} exited with status {status}", args.join(" ")),
    ))
}

fn generate_ui_assets_module(dist_root: &Path, out_file: &Path) -> std::io::Result<()> {
    if !dist_root.exists() {
        return Err(Error::new(
            ErrorKind::NotFound,
            format!("bundled UI build output {} does not exist", dist_root.display()),
        ));
    }

    let mut asset_files = Vec::<PathBuf>::new();
    collect_files(dist_root, &mut asset_files)?;
    asset_files.sort();

    let has_index_html = asset_files
        .iter()
        .any(|path| path.file_name() == Some(OsStr::new("index.html")));
    if !has_index_html {
        return Err(Error::new(
            ErrorKind::InvalidData,
            format!("bundled UI output {} is missing index.html", dist_root.display()),
        ));
    }

    let mut generated = String::from("// @generated by build.rs\n");
    generated.push_str("pub static APP_UI_ASSETS: &[golden_core::app::UiAsset] = &[\n");

    for asset_path in asset_files {
        let relative_path = asset_path.strip_prefix(dist_root).map_err(|err| {
            Error::new(
                ErrorKind::InvalidInput,
                format!(
                    "failed to compute bundled UI asset path relative to {} for {}: {err}",
                    dist_root.display(),
                    asset_path.display()
                ),
            )
        })?;
        let http_path = format!("/{}", relative_path.to_string_lossy().replace('\\', "/"));
        let content_type = content_type_for_path(relative_path);
        let absolute_path = asset_path.canonicalize()?;

        generated.push_str("    golden_core::app::UiAsset {\n");
        generated.push_str(&format!("        path: {:?},\n", http_path));
        generated.push_str(&format!("        content_type: {:?},\n", content_type));
        generated.push_str(&format!(
            "        bytes: include_bytes!(r#\"{}\"#),\n",
            absolute_path.display()
        ));
        generated.push_str("    },\n");
    }

    generated.push_str("];\n");
    fs::write(out_file, generated)
}

fn collect_files(dir: &Path, output: &mut Vec<PathBuf>) -> std::io::Result<()> {
    let mut entries = fs::read_dir(dir)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, output)?;
        } else {
            output.push(path);
        }
    }

    Ok(())
}

fn content_type_for_path(path: &Path) -> &'static str {
    match path
        .extension()
        .and_then(OsStr::to_str)
        .map(|ext| ext.to_ascii_lowercase())
    {
        Some(ext) => match ext.as_str() {
            "css" => "text/css; charset=utf-8",
            "gif" => "image/gif",
            "html" => "text/html; charset=utf-8",
            "ico" => "image/x-icon",
            "jpeg" | "jpg" => "image/jpeg",
            "js" => "text/javascript; charset=utf-8",
            "json" => "application/json; charset=utf-8",
            "map" => "application/json; charset=utf-8",
            "png" => "image/png",
            "svg" => "image/svg+xml",
            "txt" => "text/plain; charset=utf-8",
            "webp" => "image/webp",
            "woff" => "font/woff",
            "woff2" => "font/woff2",
            "ttf" => "font/ttf",
            _ => "application/octet-stream",
        },
        None => "application/octet-stream",
    }
}
