#[cfg(not(windows))]
use device_query::Keycode;
use golden_core::parameter::{ParamValue, ParameterEnumOption};
use rdev::Key as RdevKey;
use serde::{Deserialize, Serialize};

pub(crate) const KEYBOARD_KEY_COMMAND_NODE_TYPE: &str = "keyboard_key_command";

pub(crate) const KEYBOARD_ACTION_TAP: &str = "tap";
pub(crate) const KEYBOARD_ACTION_PRESS: &str = "press";
pub(crate) const KEYBOARD_ACTION_RELEASE: &str = "release";

pub(crate) const KEYBOARD_KEY_SPACE: &str = "space";

pub(crate) const KEYBOARD_MODULE_COMMAND_TYPES: &[&str] = &[KEYBOARD_KEY_COMMAND_NODE_TYPE];

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub(crate) enum KeyboardKey {
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Escape,
    Space,
    Enter,
    Tab,
    Backspace,
    Up,
    Down,
    Left,
    Right,
    Home,
    End,
    PageUp,
    PageDown,
    Insert,
    Delete,
    LeftControl,
    RightControl,
    LeftShift,
    RightShift,
    LeftAlt,
    RightAlt,
    LeftMeta,
    RightMeta,
    CapsLock,
    Grave,
    Minus,
    Equal,
    LeftBracket,
    RightBracket,
    BackSlash,
    Semicolon,
    Apostrophe,
    Comma,
    Dot,
    Slash,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadSubtract,
    NumpadMultiply,
    NumpadDivide,
    NumpadDecimal,
    NumpadEnter,
}

impl KeyboardKey {
    pub(crate) const ALL: &'static [Self] = &[
        Self::Digit0,
        Self::Digit1,
        Self::Digit2,
        Self::Digit3,
        Self::Digit4,
        Self::Digit5,
        Self::Digit6,
        Self::Digit7,
        Self::Digit8,
        Self::Digit9,
        Self::A,
        Self::B,
        Self::C,
        Self::D,
        Self::E,
        Self::F,
        Self::G,
        Self::H,
        Self::I,
        Self::J,
        Self::K,
        Self::L,
        Self::M,
        Self::N,
        Self::O,
        Self::P,
        Self::Q,
        Self::R,
        Self::S,
        Self::T,
        Self::U,
        Self::V,
        Self::W,
        Self::X,
        Self::Y,
        Self::Z,
        Self::F1,
        Self::F2,
        Self::F3,
        Self::F4,
        Self::F5,
        Self::F6,
        Self::F7,
        Self::F8,
        Self::F9,
        Self::F10,
        Self::F11,
        Self::F12,
        Self::Escape,
        Self::Space,
        Self::Enter,
        Self::Tab,
        Self::Backspace,
        Self::Up,
        Self::Down,
        Self::Left,
        Self::Right,
        Self::Home,
        Self::End,
        Self::PageUp,
        Self::PageDown,
        Self::Insert,
        Self::Delete,
        Self::LeftControl,
        Self::RightControl,
        Self::LeftShift,
        Self::RightShift,
        Self::LeftAlt,
        Self::RightAlt,
        Self::LeftMeta,
        Self::RightMeta,
        Self::CapsLock,
        Self::Grave,
        Self::Minus,
        Self::Equal,
        Self::LeftBracket,
        Self::RightBracket,
        Self::BackSlash,
        Self::Semicolon,
        Self::Apostrophe,
        Self::Comma,
        Self::Dot,
        Self::Slash,
        Self::Numpad0,
        Self::Numpad1,
        Self::Numpad2,
        Self::Numpad3,
        Self::Numpad4,
        Self::Numpad5,
        Self::Numpad6,
        Self::Numpad7,
        Self::Numpad8,
        Self::Numpad9,
        Self::NumpadAdd,
        Self::NumpadSubtract,
        Self::NumpadMultiply,
        Self::NumpadDivide,
        Self::NumpadDecimal,
        Self::NumpadEnter,
    ];

    pub(crate) fn parse(value: &str) -> Result<Self, String> {
        if value.trim().is_empty() {
            return Err("keyboard key cannot be empty".to_string());
        }

        let normalized = normalize_key_identifier(value);
        let key = match normalized.as_str() {
            "0" | "digit0" | "digit_0" => Self::Digit0,
            "1" | "digit1" | "digit_1" => Self::Digit1,
            "2" | "digit2" | "digit_2" => Self::Digit2,
            "3" | "digit3" | "digit_3" => Self::Digit3,
            "4" | "digit4" | "digit_4" => Self::Digit4,
            "5" | "digit5" | "digit_5" => Self::Digit5,
            "6" | "digit6" | "digit_6" => Self::Digit6,
            "7" | "digit7" | "digit_7" => Self::Digit7,
            "8" | "digit8" | "digit_8" => Self::Digit8,
            "9" | "digit9" | "digit_9" => Self::Digit9,
            "a" => Self::A,
            "b" => Self::B,
            "c" => Self::C,
            "d" => Self::D,
            "e" => Self::E,
            "f" => Self::F,
            "g" => Self::G,
            "h" => Self::H,
            "i" => Self::I,
            "j" => Self::J,
            "k" => Self::K,
            "l" => Self::L,
            "m" => Self::M,
            "n" => Self::N,
            "o" => Self::O,
            "p" => Self::P,
            "q" => Self::Q,
            "r" => Self::R,
            "s" => Self::S,
            "t" => Self::T,
            "u" => Self::U,
            "v" => Self::V,
            "w" => Self::W,
            "x" => Self::X,
            "y" => Self::Y,
            "z" => Self::Z,
            "f1" => Self::F1,
            "f2" => Self::F2,
            "f3" => Self::F3,
            "f4" => Self::F4,
            "f5" => Self::F5,
            "f6" => Self::F6,
            "f7" => Self::F7,
            "f8" => Self::F8,
            "f9" => Self::F9,
            "f10" => Self::F10,
            "f11" => Self::F11,
            "f12" => Self::F12,
            "escape" | "esc" => Self::Escape,
            "space" => Self::Space,
            "enter" | "return" => Self::Enter,
            "tab" => Self::Tab,
            "backspace" | "back_space" => Self::Backspace,
            "up" | "up_arrow" => Self::Up,
            "down" | "down_arrow" => Self::Down,
            "left" | "left_arrow" => Self::Left,
            "right" | "right_arrow" => Self::Right,
            "home" => Self::Home,
            "end" => Self::End,
            "page_up" | "pageup" => Self::PageUp,
            "page_down" | "pagedown" => Self::PageDown,
            "insert" => Self::Insert,
            "delete" => Self::Delete,
            "left_control" | "control_left" | "left_ctrl" | "ctrl_left" | "ctrl" | "control" => {
                Self::LeftControl
            }
            "right_control" | "control_right" | "right_ctrl" | "ctrl_right" => Self::RightControl,
            "left_shift" | "shift_left" | "shift" => Self::LeftShift,
            "right_shift" | "shift_right" => Self::RightShift,
            "left_alt" | "alt_left" | "alt" => Self::LeftAlt,
            "right_alt" | "alt_right" | "altgr" => Self::RightAlt,
            "left_meta" | "meta_left" | "command" | "super" | "windows" => Self::LeftMeta,
            "right_meta" | "meta_right" | "right_command" | "right_super" | "right_windows" => {
                Self::RightMeta
            }
            "caps_lock" | "capslock" | "caps" => Self::CapsLock,
            "grave" | "backquote" | "back_quote" => Self::Grave,
            "minus" => Self::Minus,
            "equal" | "equals" => Self::Equal,
            "left_bracket" | "open_bracket" => Self::LeftBracket,
            "right_bracket" | "close_bracket" => Self::RightBracket,
            "backslash" | "back_slash" => Self::BackSlash,
            "semicolon" | "semi_colon" => Self::Semicolon,
            "apostrophe" | "quote" => Self::Apostrophe,
            "comma" => Self::Comma,
            "dot" | "period" => Self::Dot,
            "slash" | "forward_slash" => Self::Slash,
            "numpad_0" | "kp0" => Self::Numpad0,
            "numpad_1" | "kp1" => Self::Numpad1,
            "numpad_2" | "kp2" => Self::Numpad2,
            "numpad_3" | "kp3" => Self::Numpad3,
            "numpad_4" | "kp4" => Self::Numpad4,
            "numpad_5" | "kp5" => Self::Numpad5,
            "numpad_6" | "kp6" => Self::Numpad6,
            "numpad_7" | "kp7" => Self::Numpad7,
            "numpad_8" | "kp8" => Self::Numpad8,
            "numpad_9" | "kp9" => Self::Numpad9,
            "numpad_add" | "kp_plus" | "keypad_add" => Self::NumpadAdd,
            "numpad_subtract" | "kp_minus" | "keypad_subtract" => Self::NumpadSubtract,
            "numpad_multiply" | "kp_multiply" | "keypad_multiply" => Self::NumpadMultiply,
            "numpad_divide" | "kp_divide" | "keypad_divide" => Self::NumpadDivide,
            "numpad_decimal" | "kp_decimal" | "keypad_decimal" => Self::NumpadDecimal,
            "numpad_enter" | "kp_enter" | "keypad_enter" => Self::NumpadEnter,
            _ => {
                return Err(format!(
                    "unsupported keyboard key '{value}', use a supported physical key id like 'a', 'space', 'enter', 'left_control', or 'numpad_1'"
                ));
            }
        };

        Ok(key)
    }

    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::Digit0 => "0",
            Self::Digit1 => "1",
            Self::Digit2 => "2",
            Self::Digit3 => "3",
            Self::Digit4 => "4",
            Self::Digit5 => "5",
            Self::Digit6 => "6",
            Self::Digit7 => "7",
            Self::Digit8 => "8",
            Self::Digit9 => "9",
            Self::A => "a",
            Self::B => "b",
            Self::C => "c",
            Self::D => "d",
            Self::E => "e",
            Self::F => "f",
            Self::G => "g",
            Self::H => "h",
            Self::I => "i",
            Self::J => "j",
            Self::K => "k",
            Self::L => "l",
            Self::M => "m",
            Self::N => "n",
            Self::O => "o",
            Self::P => "p",
            Self::Q => "q",
            Self::R => "r",
            Self::S => "s",
            Self::T => "t",
            Self::U => "u",
            Self::V => "v",
            Self::W => "w",
            Self::X => "x",
            Self::Y => "y",
            Self::Z => "z",
            Self::F1 => "f1",
            Self::F2 => "f2",
            Self::F3 => "f3",
            Self::F4 => "f4",
            Self::F5 => "f5",
            Self::F6 => "f6",
            Self::F7 => "f7",
            Self::F8 => "f8",
            Self::F9 => "f9",
            Self::F10 => "f10",
            Self::F11 => "f11",
            Self::F12 => "f12",
            Self::Escape => "escape",
            Self::Space => KEYBOARD_KEY_SPACE,
            Self::Enter => "enter",
            Self::Tab => "tab",
            Self::Backspace => "backspace",
            Self::Up => "up",
            Self::Down => "down",
            Self::Left => "left",
            Self::Right => "right",
            Self::Home => "home",
            Self::End => "end",
            Self::PageUp => "page_up",
            Self::PageDown => "page_down",
            Self::Insert => "insert",
            Self::Delete => "delete",
            Self::LeftControl => "left_control",
            Self::RightControl => "right_control",
            Self::LeftShift => "left_shift",
            Self::RightShift => "right_shift",
            Self::LeftAlt => "left_alt",
            Self::RightAlt => "right_alt",
            Self::LeftMeta => "left_meta",
            Self::RightMeta => "right_meta",
            Self::CapsLock => "caps_lock",
            Self::Grave => "grave",
            Self::Minus => "minus",
            Self::Equal => "equal",
            Self::LeftBracket => "left_bracket",
            Self::RightBracket => "right_bracket",
            Self::BackSlash => "backslash",
            Self::Semicolon => "semicolon",
            Self::Apostrophe => "apostrophe",
            Self::Comma => "comma",
            Self::Dot => "dot",
            Self::Slash => "slash",
            Self::Numpad0 => "numpad_0",
            Self::Numpad1 => "numpad_1",
            Self::Numpad2 => "numpad_2",
            Self::Numpad3 => "numpad_3",
            Self::Numpad4 => "numpad_4",
            Self::Numpad5 => "numpad_5",
            Self::Numpad6 => "numpad_6",
            Self::Numpad7 => "numpad_7",
            Self::Numpad8 => "numpad_8",
            Self::Numpad9 => "numpad_9",
            Self::NumpadAdd => "numpad_add",
            Self::NumpadSubtract => "numpad_subtract",
            Self::NumpadMultiply => "numpad_multiply",
            Self::NumpadDivide => "numpad_divide",
            Self::NumpadDecimal => "numpad_decimal",
            Self::NumpadEnter => "numpad_enter",
        }
    }

    pub(crate) fn label(self) -> &'static str {
        match self {
            Self::Digit0 => "0",
            Self::Digit1 => "1",
            Self::Digit2 => "2",
            Self::Digit3 => "3",
            Self::Digit4 => "4",
            Self::Digit5 => "5",
            Self::Digit6 => "6",
            Self::Digit7 => "7",
            Self::Digit8 => "8",
            Self::Digit9 => "9",
            Self::A => "A",
            Self::B => "B",
            Self::C => "C",
            Self::D => "D",
            Self::E => "E",
            Self::F => "F",
            Self::G => "G",
            Self::H => "H",
            Self::I => "I",
            Self::J => "J",
            Self::K => "K",
            Self::L => "L",
            Self::M => "M",
            Self::N => "N",
            Self::O => "O",
            Self::P => "P",
            Self::Q => "Q",
            Self::R => "R",
            Self::S => "S",
            Self::T => "T",
            Self::U => "U",
            Self::V => "V",
            Self::W => "W",
            Self::X => "X",
            Self::Y => "Y",
            Self::Z => "Z",
            Self::F1 => "F1",
            Self::F2 => "F2",
            Self::F3 => "F3",
            Self::F4 => "F4",
            Self::F5 => "F5",
            Self::F6 => "F6",
            Self::F7 => "F7",
            Self::F8 => "F8",
            Self::F9 => "F9",
            Self::F10 => "F10",
            Self::F11 => "F11",
            Self::F12 => "F12",
            Self::Escape => "Escape",
            Self::Space => "Space",
            Self::Enter => "Enter",
            Self::Tab => "Tab",
            Self::Backspace => "Backspace",
            Self::Up => "Up",
            Self::Down => "Down",
            Self::Left => "Left",
            Self::Right => "Right",
            Self::Home => "Home",
            Self::End => "End",
            Self::PageUp => "Page Up",
            Self::PageDown => "Page Down",
            Self::Insert => "Insert",
            Self::Delete => "Delete",
            Self::LeftControl => "Left Control",
            Self::RightControl => "Right Control",
            Self::LeftShift => "Left Shift",
            Self::RightShift => "Right Shift",
            Self::LeftAlt => "Left Alt",
            Self::RightAlt => "Right Alt",
            Self::LeftMeta => "Left Meta",
            Self::RightMeta => "Right Meta",
            Self::CapsLock => "Caps Lock",
            Self::Grave => "Grave",
            Self::Minus => "Minus",
            Self::Equal => "Equal",
            Self::LeftBracket => "Left Bracket",
            Self::RightBracket => "Right Bracket",
            Self::BackSlash => "Backslash",
            Self::Semicolon => "Semicolon",
            Self::Apostrophe => "Apostrophe",
            Self::Comma => "Comma",
            Self::Dot => "Dot",
            Self::Slash => "Slash",
            Self::Numpad0 => "Numpad 0",
            Self::Numpad1 => "Numpad 1",
            Self::Numpad2 => "Numpad 2",
            Self::Numpad3 => "Numpad 3",
            Self::Numpad4 => "Numpad 4",
            Self::Numpad5 => "Numpad 5",
            Self::Numpad6 => "Numpad 6",
            Self::Numpad7 => "Numpad 7",
            Self::Numpad8 => "Numpad 8",
            Self::Numpad9 => "Numpad 9",
            Self::NumpadAdd => "Numpad Add",
            Self::NumpadSubtract => "Numpad Subtract",
            Self::NumpadMultiply => "Numpad Multiply",
            Self::NumpadDivide => "Numpad Divide",
            Self::NumpadDecimal => "Numpad Decimal",
            Self::NumpadEnter => "Numpad Enter",
        }
    }

    #[cfg(not(windows))]
    pub(crate) fn from_device_query(key: Keycode) -> Option<Self> {
        match key {
            Keycode::Key0 => Some(Self::Digit0),
            Keycode::Key1 => Some(Self::Digit1),
            Keycode::Key2 => Some(Self::Digit2),
            Keycode::Key3 => Some(Self::Digit3),
            Keycode::Key4 => Some(Self::Digit4),
            Keycode::Key5 => Some(Self::Digit5),
            Keycode::Key6 => Some(Self::Digit6),
            Keycode::Key7 => Some(Self::Digit7),
            Keycode::Key8 => Some(Self::Digit8),
            Keycode::Key9 => Some(Self::Digit9),
            Keycode::A => Some(Self::A),
            Keycode::B => Some(Self::B),
            Keycode::C => Some(Self::C),
            Keycode::D => Some(Self::D),
            Keycode::E => Some(Self::E),
            Keycode::F => Some(Self::F),
            Keycode::G => Some(Self::G),
            Keycode::H => Some(Self::H),
            Keycode::I => Some(Self::I),
            Keycode::J => Some(Self::J),
            Keycode::K => Some(Self::K),
            Keycode::L => Some(Self::L),
            Keycode::M => Some(Self::M),
            Keycode::N => Some(Self::N),
            Keycode::O => Some(Self::O),
            Keycode::P => Some(Self::P),
            Keycode::Q => Some(Self::Q),
            Keycode::R => Some(Self::R),
            Keycode::S => Some(Self::S),
            Keycode::T => Some(Self::T),
            Keycode::U => Some(Self::U),
            Keycode::V => Some(Self::V),
            Keycode::W => Some(Self::W),
            Keycode::X => Some(Self::X),
            Keycode::Y => Some(Self::Y),
            Keycode::Z => Some(Self::Z),
            Keycode::F1 => Some(Self::F1),
            Keycode::F2 => Some(Self::F2),
            Keycode::F3 => Some(Self::F3),
            Keycode::F4 => Some(Self::F4),
            Keycode::F5 => Some(Self::F5),
            Keycode::F6 => Some(Self::F6),
            Keycode::F7 => Some(Self::F7),
            Keycode::F8 => Some(Self::F8),
            Keycode::F9 => Some(Self::F9),
            Keycode::F10 => Some(Self::F10),
            Keycode::F11 => Some(Self::F11),
            Keycode::F12 => Some(Self::F12),
            Keycode::Escape => Some(Self::Escape),
            Keycode::Space => Some(Self::Space),
            Keycode::LControl => Some(Self::LeftControl),
            Keycode::RControl => Some(Self::RightControl),
            Keycode::LShift => Some(Self::LeftShift),
            Keycode::RShift => Some(Self::RightShift),
            Keycode::LAlt | Keycode::LOption => Some(Self::LeftAlt),
            Keycode::RAlt | Keycode::ROption => Some(Self::RightAlt),
            Keycode::Command | Keycode::LMeta => Some(Self::LeftMeta),
            Keycode::RCommand | Keycode::RMeta => Some(Self::RightMeta),
            Keycode::Enter => Some(Self::Enter),
            Keycode::Up => Some(Self::Up),
            Keycode::Down => Some(Self::Down),
            Keycode::Left => Some(Self::Left),
            Keycode::Right => Some(Self::Right),
            Keycode::Backspace => Some(Self::Backspace),
            Keycode::CapsLock => Some(Self::CapsLock),
            Keycode::Tab => Some(Self::Tab),
            Keycode::Home => Some(Self::Home),
            Keycode::End => Some(Self::End),
            Keycode::PageUp => Some(Self::PageUp),
            Keycode::PageDown => Some(Self::PageDown),
            Keycode::Insert => Some(Self::Insert),
            Keycode::Delete => Some(Self::Delete),
            Keycode::Numpad0 => Some(Self::Numpad0),
            Keycode::Numpad1 => Some(Self::Numpad1),
            Keycode::Numpad2 => Some(Self::Numpad2),
            Keycode::Numpad3 => Some(Self::Numpad3),
            Keycode::Numpad4 => Some(Self::Numpad4),
            Keycode::Numpad5 => Some(Self::Numpad5),
            Keycode::Numpad6 => Some(Self::Numpad6),
            Keycode::Numpad7 => Some(Self::Numpad7),
            Keycode::Numpad8 => Some(Self::Numpad8),
            Keycode::Numpad9 => Some(Self::Numpad9),
            Keycode::NumpadSubtract => Some(Self::NumpadSubtract),
            Keycode::NumpadAdd => Some(Self::NumpadAdd),
            Keycode::NumpadDivide => Some(Self::NumpadDivide),
            Keycode::NumpadMultiply => Some(Self::NumpadMultiply),
            Keycode::NumpadEnter => Some(Self::NumpadEnter),
            Keycode::NumpadDecimal => Some(Self::NumpadDecimal),
            Keycode::Grave => Some(Self::Grave),
            Keycode::Minus => Some(Self::Minus),
            Keycode::Equal => Some(Self::Equal),
            Keycode::LeftBracket => Some(Self::LeftBracket),
            Keycode::RightBracket => Some(Self::RightBracket),
            Keycode::BackSlash => Some(Self::BackSlash),
            Keycode::Semicolon => Some(Self::Semicolon),
            Keycode::Apostrophe => Some(Self::Apostrophe),
            Keycode::Comma => Some(Self::Comma),
            Keycode::Dot => Some(Self::Dot),
            Keycode::Slash => Some(Self::Slash),
            _ => None,
        }
    }

    pub(crate) fn to_rdev(self) -> RdevKey {
        match self {
            Self::Digit0 => RdevKey::Num0,
            Self::Digit1 => RdevKey::Num1,
            Self::Digit2 => RdevKey::Num2,
            Self::Digit3 => RdevKey::Num3,
            Self::Digit4 => RdevKey::Num4,
            Self::Digit5 => RdevKey::Num5,
            Self::Digit6 => RdevKey::Num6,
            Self::Digit7 => RdevKey::Num7,
            Self::Digit8 => RdevKey::Num8,
            Self::Digit9 => RdevKey::Num9,
            Self::A => RdevKey::KeyA,
            Self::B => RdevKey::KeyB,
            Self::C => RdevKey::KeyC,
            Self::D => RdevKey::KeyD,
            Self::E => RdevKey::KeyE,
            Self::F => RdevKey::KeyF,
            Self::G => RdevKey::KeyG,
            Self::H => RdevKey::KeyH,
            Self::I => RdevKey::KeyI,
            Self::J => RdevKey::KeyJ,
            Self::K => RdevKey::KeyK,
            Self::L => RdevKey::KeyL,
            Self::M => RdevKey::KeyM,
            Self::N => RdevKey::KeyN,
            Self::O => RdevKey::KeyO,
            Self::P => RdevKey::KeyP,
            Self::Q => RdevKey::KeyQ,
            Self::R => RdevKey::KeyR,
            Self::S => RdevKey::KeyS,
            Self::T => RdevKey::KeyT,
            Self::U => RdevKey::KeyU,
            Self::V => RdevKey::KeyV,
            Self::W => RdevKey::KeyW,
            Self::X => RdevKey::KeyX,
            Self::Y => RdevKey::KeyY,
            Self::Z => RdevKey::KeyZ,
            Self::F1 => RdevKey::F1,
            Self::F2 => RdevKey::F2,
            Self::F3 => RdevKey::F3,
            Self::F4 => RdevKey::F4,
            Self::F5 => RdevKey::F5,
            Self::F6 => RdevKey::F6,
            Self::F7 => RdevKey::F7,
            Self::F8 => RdevKey::F8,
            Self::F9 => RdevKey::F9,
            Self::F10 => RdevKey::F10,
            Self::F11 => RdevKey::F11,
            Self::F12 => RdevKey::F12,
            Self::Escape => RdevKey::Escape,
            Self::Space => RdevKey::Space,
            Self::Enter => RdevKey::Return,
            Self::Tab => RdevKey::Tab,
            Self::Backspace => RdevKey::Backspace,
            Self::Up => RdevKey::UpArrow,
            Self::Down => RdevKey::DownArrow,
            Self::Left => RdevKey::LeftArrow,
            Self::Right => RdevKey::RightArrow,
            Self::Home => RdevKey::Home,
            Self::End => RdevKey::End,
            Self::PageUp => RdevKey::PageUp,
            Self::PageDown => RdevKey::PageDown,
            Self::Insert => RdevKey::Insert,
            Self::Delete => RdevKey::Delete,
            Self::LeftControl => RdevKey::ControlLeft,
            Self::RightControl => RdevKey::ControlRight,
            Self::LeftShift => RdevKey::ShiftLeft,
            Self::RightShift => RdevKey::ShiftRight,
            Self::LeftAlt => RdevKey::Alt,
            Self::RightAlt => RdevKey::AltGr,
            Self::LeftMeta => RdevKey::MetaLeft,
            Self::RightMeta => RdevKey::MetaRight,
            Self::CapsLock => RdevKey::CapsLock,
            Self::Grave => RdevKey::BackQuote,
            Self::Minus => RdevKey::Minus,
            Self::Equal => RdevKey::Equal,
            Self::LeftBracket => RdevKey::LeftBracket,
            Self::RightBracket => RdevKey::RightBracket,
            Self::BackSlash => RdevKey::BackSlash,
            Self::Semicolon => RdevKey::SemiColon,
            Self::Apostrophe => RdevKey::Quote,
            Self::Comma => RdevKey::Comma,
            Self::Dot => RdevKey::Dot,
            Self::Slash => RdevKey::Slash,
            Self::Numpad0 => RdevKey::Kp0,
            Self::Numpad1 => RdevKey::Kp1,
            Self::Numpad2 => RdevKey::Kp2,
            Self::Numpad3 => RdevKey::Kp3,
            Self::Numpad4 => RdevKey::Kp4,
            Self::Numpad5 => RdevKey::Kp5,
            Self::Numpad6 => RdevKey::Kp6,
            Self::Numpad7 => RdevKey::Kp7,
            Self::Numpad8 => RdevKey::Kp8,
            Self::Numpad9 => RdevKey::Kp9,
            Self::NumpadAdd => RdevKey::KpPlus,
            Self::NumpadSubtract => RdevKey::KpMinus,
            Self::NumpadMultiply => RdevKey::KpMultiply,
            Self::NumpadDivide => RdevKey::KpDivide,
            Self::NumpadDecimal => RdevKey::KpDelete,
            Self::NumpadEnter => RdevKey::KpReturn,
        }
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum KeyboardKeyAction {
    Tap,
    Press,
    Release,
}

impl KeyboardKeyAction {
    pub(crate) fn parse(value: &str) -> Result<Self, String> {
        match normalize_key_identifier(value).as_str() {
            KEYBOARD_ACTION_TAP => Ok(Self::Tap),
            KEYBOARD_ACTION_PRESS => Ok(Self::Press),
            KEYBOARD_ACTION_RELEASE => Ok(Self::Release),
            _ => Err(format!(
                "unsupported keyboard key action '{value}', expected '{KEYBOARD_ACTION_TAP}', '{KEYBOARD_ACTION_PRESS}', or '{KEYBOARD_ACTION_RELEASE}'"
            )),
        }
    }

    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::Tap => KEYBOARD_ACTION_TAP,
            Self::Press => KEYBOARD_ACTION_PRESS,
            Self::Release => KEYBOARD_ACTION_RELEASE,
        }
    }

    pub(crate) fn label(self) -> &'static str {
        match self {
            Self::Tap => "Tap",
            Self::Press => "Press",
            Self::Release => "Release",
        }
    }

    pub(crate) fn summary_label(self) -> &'static str {
        match self {
            Self::Tap => "Tapped",
            Self::Press => "Pressed",
            Self::Release => "Released",
        }
    }
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub(crate) struct KeyboardKeyRequest {
    pub key: String,
    pub action: KeyboardKeyAction,
    pub description: String,
}

pub(crate) fn keyboard_key_enum_options() -> Vec<ParameterEnumOption> {
    KeyboardKey::ALL
        .iter()
        .copied()
        .enumerate()
        .map(|(ordering, key)| ParameterEnumOption {
            variant_id: key.as_str().to_string(),
            value: ParamValue::Enum(key.as_str().to_string()),
            label: key.label().to_string(),
            tags: Vec::new(),
            ordering: Some(ordering as i32),
        })
        .collect()
}

pub(crate) fn keyboard_key_action_enum_options() -> Vec<ParameterEnumOption> {
    [
        (KEYBOARD_ACTION_TAP, KeyboardKeyAction::Tap.label()),
        (KEYBOARD_ACTION_PRESS, KeyboardKeyAction::Press.label()),
        (KEYBOARD_ACTION_RELEASE, KeyboardKeyAction::Release.label()),
    ]
    .into_iter()
    .enumerate()
    .map(|(ordering, (variant_id, label))| ParameterEnumOption {
        variant_id: variant_id.to_string(),
        value: ParamValue::Enum(variant_id.to_string()),
        label: label.to_string(),
        tags: Vec::new(),
        ordering: Some(ordering as i32),
    })
    .collect()
}

fn normalize_key_identifier(value: &str) -> String {
    value
        .trim()
        .to_ascii_lowercase()
        .replace(' ', "_")
        .replace('-', "_")
}