[package]
name = "chataigne_condition"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["serde"]
serde = ["dep:serde", "golden_values/serde"]

[dependencies]
golden_values.workspace = true
indexmap.workspace = true
regex.workspace = true
serde = { workspace = true, optional = true }
sha2.workspace = true
thiserror.workspace = true
uuid.workspace = true
