[package]
name = "golden_script"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
golden_model.workspace = true
golden_parameters.workspace = true
golden_script_contract.workspace = true
rquickjs = { version = "0.11", features = ["parallel"] }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde_json.workspace = true

[target.'cfg(all(target_os = "linux", target_arch = "arm"))'.dependencies]
rquickjs = { version = "0.11", features = ["parallel", "bindgen"] }
