[package]
name = "golden-processor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
golden-alchemist.workspace = true
golden-condition.workspace = true
golden-context.workspace = true
golden-model.workspace = true
golden-values.workspace = true
smol_str.workspace = true
thiserror.workspace = true
uuid.workspace = true
