use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
struct NodeEntry {
    module: String,
    type_name: String,
    source_path: String,
}

pub fn generate_app_nodes(src_root: &Path, out_file: &Path) {
    println!("cargo:rerun-if-changed={}", src_root.display());

    let mut rust_files = Vec::new();
    collect_rs_files(src_root, &mut rust_files);
    rust_files.sort();

    let mut entries = Vec::new();
    for path in rust_files {
        println!("cargo:rerun-if-changed={}", path.display());

        let source = fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("failed to read {}: {}", path.display(), err));

        // Only files declaring node types through the shared macro are auto-registered.
        if !source.contains("define_node_type!") {
            continue;
        }

        let type_name = extract_struct_name(&source).unwrap_or_else(|| {
            panic!(
                "could not find `struct <Type>` in {} (expected inside define_node_type!)",
                path.display()
            )
        });

        let module = module_name_from_relative(src_root, &path);
        let source_path = normalize_absolute_path(
            path.canonicalize()
                .unwrap_or_else(|err| panic!("failed to canonicalize {}: {}", path.display(), err)),
        );

        entries.push(NodeEntry {
            module,
            type_name,
            source_path,
        });
    }

    entries.sort_by(|a, b| a.type_name.cmp(&b.type_name));
    ensure_unique_type_names(&entries);

    let generated = render_registry(&entries);
    fs::write(out_file, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {}", out_file.display(), err));
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) {
    if !dir.exists() {
        return;
    }

    let read_dir = fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("failed to read {}: {}", dir.display(), err));

    for entry in read_dir {
        let entry = entry.unwrap_or_else(|err| panic!("failed to read dir entry: {}", err));
        let path = entry.path();

        if path.is_dir() {
            collect_rs_files(&path, out);
            continue;
        }

        if is_rust_file(&path) {
            out.push(path);
        }
    }
}

fn is_rust_file(path: &Path) -> bool {
    path.is_file() && matches!(path.extension().and_then(|ext| ext.to_str()), Some("rs"))
}

fn extract_struct_name(source: &str) -> Option<String> {
    extract_after_marker(source, "pub struct ").or_else(|| extract_after_marker(source, "struct "))
}

fn extract_after_marker(source: &str, marker: &str) -> Option<String> {
    let marker_pos = source.find(marker)?;
    let start = marker_pos + marker.len();
    let tail = &source[start..];

    let ident: String = tail
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();

    if ident.is_empty() {
        None
    } else {
        Some(ident)
    }
}

fn module_name_from_relative(src_root: &Path, file: &Path) -> String {
    let relative = file.strip_prefix(src_root).unwrap_or_else(|_| {
        panic!(
            "failed to compute relative path for {} from {}",
            file.display(),
            src_root.display()
        )
    });

    let mut module = String::new();
    for component in relative.components() {
        let s = component.as_os_str().to_string_lossy();
        if s.eq_ignore_ascii_case("mod.rs") {
            continue;
        }

        let stem = if s.ends_with(".rs") {
            &s[..s.len() - 3]
        } else {
            &s
        };

        if module.is_empty() {
            module.push_str(&sanitize_ident_part(stem));
        } else {
            module.push('_');
            module.push_str(&sanitize_ident_part(stem));
        }
    }

    module
}

fn sanitize_ident_part(input: &str) -> String {
    let mut out = String::new();
    for c in input.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }

    if out.is_empty() {
        out.push_str("node");
    }

    out
}

fn ensure_unique_type_names(entries: &[NodeEntry]) {
    let mut seen = HashSet::new();
    for entry in entries {
        if !seen.insert(entry.type_name.clone()) {
            panic!(
                "duplicate node type `{}` detected; node type names must be unique",
                entry.type_name
            );
        }
    }
}

fn render_registry(entries: &[NodeEntry]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs via golden_core/node/node_codegen.rs. Do not edit.\n");
    out.push_str("use golden_core::define_node_enum;\n\n");

    for entry in entries {
        out.push_str(&format!("#[path = \"{}\"]\n", entry.source_path));
        out.push_str(&format!("pub mod {};\n", entry.module));
    }

    if !entries.is_empty() {
        out.push('\n');
    }

    for entry in entries {
        out.push_str(&format!("pub use {}::{};\n", entry.module, entry.type_name));
    }

    if !entries.is_empty() {
        out.push('\n');
    }

    out.push_str("define_node_enum!(\n");
    out.push_str("    pub enum AppNode {\n");
    for entry in entries {
        out.push_str(&format!("        {},\n", entry.type_name));
    }
    out.push_str("    }\n");
    out.push_str(");\n");

    out
}

fn normalize_absolute_path(path: PathBuf) -> String {
    let normalized = path.to_string_lossy().replace('\\', "/");
    normalized.strip_prefix("//?/").unwrap_or(&normalized).to_string()
}
