[package]
name = "golden_transport_server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
golden_engine = { path = "../core" }
golden_protocol = { path = "../protocol" }
futures-util = "0.3"
mdns-sd = "0.20.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["net", "rt", "time"] }
tokio-tungstenite = "0.29"
