// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalysisDiagnosticsObservation = { captured_frames: number, processed_frames: number, dropped_frames: number, stale_frames: number, worker_time_micros: number, maximum_worker_time_micros: number, };
