// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioDeviceFingerprint = { vendor: string | null, product: string | null, serial: string | null, transport: string | null, backend_path: string | null, input_channels: number, output_channels: number, properties: { [key in string]: string }, };
