// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioErrorCategory } from "./AudioErrorCategory";

export type AudioError = { category: AudioErrorCategory, message: string, context: { [key in string]: string }, };
