// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioSampleFormat = "i8" | "f32" | "f64" | "i16" | "i24" | "i32" | "i64" | "u8" | "u16" | "u24" | "u32" | "u64";
