// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioErrorCategory = "invalid_configuration" | "unsupported_format" | "backend_unavailable" | "device_missing" | "device_busy" | "permission_denied" | "stream_negotiation_failed" | "queue_full" | "capacity_exceeded" | "decode_failed" | "playback_not_found" | "shutting_down" | "internal_invariant";
