// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioFileFormat = "wave" | "aiff" | "caf" | "flac" | "mp3" | "iso_mp4" | "ogg" | "matroska";
