// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybackObservation = { loading_voices: number, active_voices: number, command_queue_pressure_count: number, cache_entries: number, resident_bytes: number, cache_hits: number, cache_misses: number, cache_invalidations: number, cache_evictions: number, };
