// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpectrumBandObservation } from "./SpectrumBandObservation";

export type SpectrumObservation = { fft_size: number, bands: Array<SpectrumBandObservation>, };
