[package]
name = "chataigne_processor"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["serde"]
serde = []
testkit = ["dep:golden_graph"]

[dependencies]
chataigne_alchemist.workspace = true
chataigne_condition.workspace = true
golden_graph = { workspace = true, optional = true }
chataigne_state_machine_model.workspace = true
golden_values.workspace = true
indexmap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
golden_graph.workspace = true
