[package]
name = "chataigne_state_machine_model"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
golden_graph.workspace = true
indexmap.workspace = true
serde = { workspace = true, optional = true }
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
