[package]
name = "golden-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
golden-transport.workspace = true
serde.workspace = true
smol_str.workspace = true
thiserror.workspace = true

