[package]
name = "golden_codegen_support"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
golden_protocol = { path = "../protocol" }
golden_script = { path = "../script" }
ts-rs.workspace = true
