use std::marker::PhantomData;

use crate::events::EventKind;
use crate::node::{DeclId, Node, NodeId};
use crate::process_ctx::ProcessCtx;

use super::node_handle::NodeHandle;
use super::potential_node_handle::PotentialNodeHandle;

/// Strongly typed declared child slot generated by `#[children(node ...)]`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DeclaredNodeHandle<T: Node + 'static> {
    slot: PotentialNodeHandle,
    _marker: PhantomData<fn() -> T>,
}

impl<T: Node + 'static> DeclaredNodeHandle<T> {
    /// Creates an empty declared slot under `parent`.
    pub fn new(parent: NodeId, decl_id: impl Into<String>) -> Self {
        Self {
            slot: PotentialNodeHandle::new(parent, decl_id),
            _marker: PhantomData,
        }
    }

    /// Creates a declared slot with a known current runtime node id.
    pub fn with_current(parent: NodeId, decl_id: impl Into<String>, current: NodeId) -> Self {
        Self {
            slot: PotentialNodeHandle::with_current(parent, decl_id, current),
            _marker: PhantomData,
        }
    }

    /// Returns the parent node id for this slot.
    pub fn parent(&self) -> NodeId {
        self.slot.parent()
    }

    /// Rebinds the parent node for this slot.
    pub fn set_parent(&mut self, parent: NodeId) {
        self.slot.set_parent(parent);
    }

    /// Returns the declared slot id.
    pub fn decl_id(&self) -> &DeclId {
        self.slot.decl_id()
    }

    /// Returns `true` when a runtime node is currently bound to this slot.
    pub fn is_present(&self) -> bool {
        self.slot.is_present()
    }

    /// Returns `true` when this slot has queued creation and is waiting for `ChildAdded`.
    pub fn is_pending_create(&self) -> bool {
        self.slot.is_pending_create()
    }

    /// Returns the currently bound node id, when present.
    pub fn current_id(&self) -> Option<NodeId> {
        self.slot.current_id()
    }

    /// Returns a concrete node handle when this slot is present.
    pub fn get(&self) -> Option<NodeHandle> {
        self.slot.get()
    }

    /// Binds an existing node id as the current materialized slot value.
    pub fn bind_existing(&mut self, node: NodeId) {
        self.slot.bind_existing(node);
    }

    /// Detaches local knowledge of the current node id without queuing edits.
    pub fn detach_current(&mut self) -> Option<NodeId> {
        self.slot.detach_current()
    }

    /// Moves an existing node under this slot parent and marks it as current.
    pub fn attach_existing(&mut self, ctx: &mut ProcessCtx, node: NodeId, after: Option<NodeId>) {
        self.slot.attach_existing(ctx, node, after);
    }

    /// Removes the current slot node if present and clears local binding.
    pub fn clear(&mut self, ctx: &mut ProcessCtx) -> Option<NodeId> {
        self.slot.clear(ctx)
    }

    /// Queues replacement (or creation) of this slot content.
    pub fn replace_with(&mut self, ctx: &mut ProcessCtx, new_node: T) {
        self.slot.replace_with(ctx, new_node);
    }

    /// Boxed variant of [`Self::replace_with`].
    pub fn replace_with_boxed(&mut self, ctx: &mut ProcessCtx, new_node: Box<dyn Node>) {
        self.slot.replace_with_boxed(ctx, new_node);
    }

    /// Reconciles a `ChildAdded` event and binds this slot when `decl_id` matches.
    pub fn reconcile_child_added(&mut self, parent: NodeId, child: NodeId, decl_id: &DeclId) -> bool {
        self.slot.reconcile_child_added(parent, child, decl_id)
    }

    /// Reconciles a `ChildReplaced` event and binds this slot when `decl_id` matches.
    pub fn reconcile_child_replaced(&mut self, parent: NodeId, old: NodeId, new: NodeId, decl_id: &DeclId) -> bool {
        self.slot.reconcile_child_replaced(parent, old, new, decl_id)
    }

    /// Reconciles a `ChildRemoved` event and clears this slot when its current node is removed.
    pub fn reconcile_child_removed(&mut self, parent: NodeId, child: NodeId) -> bool {
        self.slot.reconcile_child_removed(parent, child)
    }

    /// Reconciles this slot from a generic engine event.
    pub fn reconcile_event(&mut self, event: &EventKind) -> bool {
        self.slot.reconcile_event(event)
    }

    /// Queues one typed mutation callback when this slot is currently present.
    ///
    /// Returns `true` when a callback was queued, `false` when this slot has no
    /// materialized runtime node yet.
    pub fn with_mut<F>(&self, ctx: &mut ProcessCtx, callback: F) -> bool
    where
        F: FnOnce(&mut T, &mut ProcessCtx) + Send + 'static,
    {
        self.slot.with_mut::<T, F>(ctx, callback)
    }
}
