// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisResult } from "./AnalysisResult";
import type { AnalysisTapId } from "./AnalysisTapId";
import type { AudioChannelId } from "./AudioChannelId";

export type AnalysisTapObservation = { tap: AnalysisTapId, source: AudioChannelId, enabled: boolean, result: AnalysisResult | null, };
