// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioErrorCategory } from "./AudioErrorCategory";

export type AudioInspectorError = { category: AudioErrorCategory, message: string, technical_detail: string | null, };
