// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioBackendState } from "./AudioBackendState";
import type { BackendId } from "./BackendId";

export type AudioBackendStatus = { backend: BackendId, label: string, state: AudioBackendState, detail: string | null, };
