// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderRuntimeObservation = { rendered_blocks: number, rendered_frames: number, render_time_micros: number, maximum_render_time_micros: number, deadline_miss_count: number, xrun_count: number, control_queue_pressure_count: number, input_underflow_count: number, input_overflow_count: number, output_underflow_count: number, output_overflow_count: number, };
