// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioDirection } from "./AudioDirection";

export type SoundCardUiControlRequest = { "kind": "stop_file", playback_id: string, } | { "kind": "stop_all_files" } | { "kind": "connect_route", direction: AudioDirection, physical_channel: string, app_channel_uuid: string, } | { "kind": "disconnect_route", direction: AudioDirection, physical_channel: string, app_channel_uuid: string, } | { "kind": "rename_channel", direction: AudioDirection, app_channel_uuid: string, label: string, };
