// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpectrumBandObservation = { index: number, low_hz: number, center_hz: number, high_hz: number, amplitude_linear: number, amplitude_dbfs: number, };
