[package]
name = "golden_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
golden_application.workspace = true
golden_context.workspace = true
golden_graph.workspace = true
golden_model.workspace = true
golden_parameters.workspace = true
golden_values.workspace = true
golden_engine = { path = "../core" }
golden_core_macros = { path = "../core_macros" }
golden_host_desktop = { path = "../host_desktop" }
golden_persistence = { path = "../persistence" }
golden_protocol = { path = "../protocol" }
golden_script = { path = "../script" }
golden_transport_server = { path = "../transport_server" }
