[package]
name = "chataigne_state_machine"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["serde"]
serde = []

[dependencies]
chataigne_alchemist.workspace = true
golden_alchemist.workspace = true
golden_statechart.workspace = true
indexmap.workspace = true
serde.workspace = true
uuid.workspace = true
